# Generated by Django 4.2 on 2025-03-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="brand_icons/"),
        ),
        migrations.AddField(
            model_name="categoryparent",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="category_icons/"),
        ),
    ]
