# Generated by Django 4.2 on 2025-04-05 16:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_brand_icon_categoryparent_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="supplier",
        ),
        migrations.AddField(
            model_name="order",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.UUIDField(default="C8BC87EEFB03417AA79E", editable=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
