# Generated by Django 4.2 on 2025-04-05 16:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_orderitem_supplier_order_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.UUIDField(default="97BABB4B448D40B69892", editable=False),
        ),
    ]
