# Generated by Django 4.2 on 2025-03-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='category_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='store.categoryparent'),
            preserve_default=False,
        ),
    ]
