# Generated by Django 4.2 on 2025-03-15 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='category_parent',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='parts',
                to='store.categoryparent',
            ),
            preserve_default=False,
        ),
    ]
