# Generated by Django 4.2 on 2025-03-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Male', 'Male'),
                    ('Female', 'Female'),
                    ('Prefer not to say', 'Prefer not to say'),
                ],
                max_length=50,
                null=True,
                verbose_name='Gender',
            ),
        ),
    ]
