# Generated by Django 4.2 on 2025-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_vat_number_user_company_name_user_is_trader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
