# Generated by Django 4.2 on 2025-03-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_traderprofile_average_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="VAT_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
        migrations.AddField(
            model_name="traderprofile",
            name="VAT_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="traderprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="traderprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
